# -*- coding: utf-8 -*-
"""Phylogenetic_Tree_Builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kz5rVl1HNxgKrrhY3umx4FM5KM4XNaAg

# 🌳 Phylogenetic Tree Builder

This project reads multiple DNA sequences from a FASTA file, computes pairwise distances, and builds a **phylogenetic tree**.

We use:
- 📏 Distance calculation
- 🌳 UPGMA clustering
- 🖼️ Tree visualization

---

✅ Tools: BioPython, Matplotlib
"""

!pip install biopython

from Bio import AlignIO, Phylo
from Bio.Phylo.TreeConstruction import DistanceCalculator, DistanceTreeConstructor
import matplotlib.pyplot as plt
from google.colab import files

"""## 📂 Upload multi-sequence FASTA file
Must contain aligned sequences (or we use simple distance).

"""

uploaded = files.upload()
fasta_file = list(uploaded.keys())[0]

alignment = AlignIO.read(fasta_file, "fasta")
print(f"✅ Alignment contains {len(alignment)} sequences, {alignment.get_alignment_length()} positions each.")

"""## 📏 Calculating distance matrix
We’ll compute % differences (identity distances).

"""

calculator = DistanceCalculator('identity')
distance_matrix = calculator.get_distance(alignment)
print(distance_matrix)

"""## 🌳 Building phylogenetic tree

"""

upgma_tree = constructor.upgma(distance_matrix)

nj_tree = constructor.nj(distance_matrix)

"""## 🖼️ Phylogenetic Tree Visualization

"""

print("🧬 UPGMA tree")
Phylo.draw(upgma_tree, do_show=True)

print("🌳 Neighbor-Joining tree")
Phylo.draw(nj_tree, do_show=True)

"""## ✅ Conclusion

We:
- Uploaded multiple sequences
- Calculated pairwise distances
- Built a UPGMA and NJ tree
- Visualized relationships as a dendrogram


"""